-- TuRu - לוג-ריצות מלא ל-scan-settlement-gaps (בקשת המשתמש, 2026-09-12, אחרי ש-Batch 1 לא
-- אפשר לדעת בדיוק כמה API calls בוצעו בו בדיעבד - התשובה העצמית של ה-Edge Function הולכת
-- ל-pg_net, שלא שומר את גוף-התגובה בפרויקט הזה). אותו דפוס בדיוק כמו source_scan_logs (0043):
-- כתיבה רק מ-Edge Function (service_role, עוקף RLS) - בלי מדיניות insert/update בכלל, כדי
-- שהלוג יהיה אמין ולא ניתן-לזיוף מכלי-ניהול/משתמש. קריאה פתוחה ל-admin/trusted_uploader.
--
-- הבחנה מפורשת בין סוגי-הבקשות (בקשת המשתמש סעיף 6: "אל תציג את כולם כ-Google calls בלבד") -
-- id_only (Nearby Search IDs-only, כמעט-חינם) / text_search (Pro-tier, יקר) / nearby_search
-- (Pro-tier, לא בשימוש כרגע ב-scan-settlement-gaps אבל קיים גם ב-playground_discovery.py
-- הישן - עמודה משותפת לשני ה-runtime) / place_details (בדיקת-תמונה, פר-גן-מיובא).
create table public.settlement_scan_runs (
  id uuid primary key default gen_random_uuid(),
  batch_number integer generated by default as identity,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'running' check (status in ('running', 'success', 'partial', 'error', 'aborted_budget', 'backfilled_estimate')),

  settlements_processed integer not null default 0,
  settlements_failed integer not null default 0,
  settlements_remaining integer,
  -- מזהי-יישוב אמיתיים (settlements.settlement_id) שנכללו ב-batch הזה בפועל - "מספיק מידע כדי
  -- לדעת אילו יישובים נכללו בכל batch" (בקשת המשתמש). לא רק שם-עיר (עלול להיות דו-משמעי).
  settlement_ids jsonb not null default '[]',

  id_only_requests integer,
  text_search_requests integer,
  nearby_search_requests integer,
  place_details_requests integer,
  total_google_requests integer,

  google_results integer,
  candidates_found integer,
  new_playgrounds integer,
  duplicates integer,
  needs_review integer,
  rejected integer,
  bug_artifacts_removed integer not null default 0,

  estimated_cost_usd numeric(10,4),
  actual_cost_usd numeric(10,4),

  last_settlement_id text,
  error_count integer not null default 0,
  error_message text,
  notes text
);

create index idx_settlement_scan_runs_started on public.settlement_scan_runs(started_at desc);

alter table public.settlement_scan_runs enable row level security;
create policy "settlement_scan_runs_read" on public.settlement_scan_runs for select
  using (public.is_admin() or public.is_trusted_uploader());
