export const ACTIVITIES = [
  {
    id: '1',
    title: 'גן פינת החמד',
    type: 'גן שעשועים',
    category: 'גן שעשועים',
    distance: '1.4 ק"מ ממך',
    city: 'תל אביב',
    region: 'תל אביב והסביבה',
    lat: 32.08, lng: 34.78,
    min_age: 2, max_age: 6,
    ageRange: 'גילאים 2-6',
    price_type: 'free', price_amount: null,
    price: 'חינם',
    duration_minutes: 90,
    indoor_outdoor: 'outdoor',
    booking_requirement: 'none',
    rating: 4.6,
    weather_suitable: ['מתאים ליום חם', 'מוצל'],
    amenities: ['שירותים', 'מקום ישיבה להורים', 'הצללה'],
    family_fit: ['מתאים לילד ולהורה', 'אפשר להשאיר את הילד'],
    availableDays: ['א', 'ב', 'ג', 'ד', 'ה', 'ו', 'ש'],
    openHours: { start: '08:00', end: '20:00' },
    hours: '08:00–20:00',
    gradient: ['#dcecfb', '#c2ddf3'],
  },
  {
    id: '2',
    title: 'פארק הירקון - פינת פיקניק',
    type: 'פארק',
    category: 'פארק',
    distance: '2.1 ק"מ ממך',
    city: 'תל אביב',
    region: 'תל אביב והסביבה',
    lat: 32.09, lng: 34.79,
    min_age: 0, max_age: 99,
    ageRange: 'גילאים הכל',
    price_type: 'free', price_amount: null,
    price: 'חינם',
    duration_minutes: 120,
    indoor_outdoor: 'outdoor',
    booking_requirement: 'none',
    rating: 4.8,
    weather_suitable: ['מתאים ליום חם'],
    amenities: ['חניה', 'מים לשתייה'],
    family_fit: ['מתאים לקבוצות', 'מתאים לאחים בגילאים שונים'],
    availableDays: ['א', 'ב', 'ג', 'ד', 'ה', 'ו', 'ש'],
    openHours: { start: '00:00', end: '23:59' },
    hours: 'פתוח 24 שעות',
    gradient: ['#faedd6', '#f3dcb0'],
    favorite: true,
  },
  {
    id: '3',
    title: 'מוזיאון הילדים הדיגיטלי',
    type: 'מקום סגור',
    category: 'מוזיאון לילדים',
    distance: '3.6 ק"מ ממך',
    city: 'חולון',
    region: 'תל אביב והסביבה',
    lat: 32.02, lng: 34.77,
    min_age: 4, max_age: 9,
    ageRange: 'גילאים 4-9',
    price_type: 'fixed', price_amount: 49,
    price: '₪49',
    duration_minutes: 120,
    indoor_outdoor: 'indoor',
    booking_requirement: 'registration_required',
    rating: 4.5,
    weather_suitable: ['ממוזג', 'מקורה'],
    amenities: ['חניה', 'שירותים נגישים', 'בית קפה', 'מיזוג'],
    family_fit: ['מתאים לילד ולהורה'],
    availableDays: ['א', 'ב', 'ג', 'ד', 'ה'],
    openHours: { start: '10:00', end: '17:00' },
    hours: '10:00–17:00',
    gradient: ['#ece0f9', '#ddc9f3'],
    visited: true,
  },
  {
    id: '4',
    title: 'סדנת בישול לילדים',
    type: 'סדנה',
    category: 'בישול',
    distance: '5.2 ק"מ ממך',
    city: 'רעננה',
    region: 'שרון',
    lat: 32.18, lng: 34.87,
    min_age: 6, max_age: 12,
    ageRange: 'גילאים 6-12',
    price_type: 'fixed', price_amount: 80,
    price: '₪80',
    duration_minutes: 90,
    indoor_outdoor: 'indoor',
    booking_requirement: 'advance_booking',
    rating: 4.9,
    weather_suitable: ['ממוזג', 'מקורה'],
    amenities: ['מיזוג', 'שירותים'],
    family_fit: ['פעילות לילדים בלבד', 'אפשר להשאיר את הילד'],
    availableDays: ['ג', 'ה'],
    openHours: { start: '16:00', end: '18:00' },
    hours: '16:00–18:00 (ג׳, ה׳)',
    gradient: ['#fde2e2', '#f8c6c6'],
  },
  {
    id: '5',
    title: 'חוף הים - פעילות מים',
    type: 'אטרקציה',
    category: 'פעילות מים',
    distance: '2.8 ק"מ ממך',
    city: 'תל אביב',
    region: 'תל אביב והסביבה',
    lat: 32.08, lng: 34.76,
    min_age: 0, max_age: 99,
    ageRange: 'גילאים הכל',
    price_type: 'free', price_amount: null,
    price: 'חינם',
    duration_minutes: 180,
    indoor_outdoor: 'outdoor',
    booking_requirement: 'none',
    rating: 4.7,
    weather_suitable: ['מתאים ליום חם', 'פעילות בחוץ בלבד'],
    amenities: ['חניה', 'שירותים', 'מים לשתייה'],
    family_fit: ['מתאים לקבוצות'],
    availableDays: ['א', 'ב', 'ג', 'ד', 'ה', 'ו', 'ש'],
    openHours: { start: '06:00', end: '20:00' },
    hours: '06:00–20:00',
    gradient: ['#d7f3ee', '#b9e8dc'],
  },
  {
    id: '6',
    title: 'ספריית הילדים - שעת סיפור',
    type: 'ספרייה',
    category: 'שעת סיפור',
    distance: '4.0 ק"מ ממך',
    city: 'פתח תקווה',
    region: 'מרכז',
    lat: 32.09, lng: 34.89,
    min_age: 1, max_age: 6,
    ageRange: 'גילאים 1-6',
    price_type: 'free', price_amount: null,
    price: 'חינם',
    duration_minutes: 45,
    indoor_outdoor: 'indoor',
    booking_requirement: 'walk_in',
    rating: 4.4,
    weather_suitable: ['ממוזג', 'מקורה'],
    amenities: ['מיזוג', 'שירותים', 'Wi-Fi'],
    family_fit: ['מתאים לילד ולהורה'],
    availableDays: ['א', 'ד'],
    openHours: { start: '17:00', end: '17:45' },
    hours: '17:00–17:45 (א׳, ד׳)',
    gradient: ['#fff3d6', '#ffe4a8'],
  },
];
